services:
  - type: web
    name: chartist-fibo-scalp-pro
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    disk:
      name: chartist-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NTFY_TOPIC
        value: emirkan_bist_alarm
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
